on:
  push:
    branches:
      - "backend"
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install Pillow
          python -m pip install django-heroku
          pip install python-dotenv
          pip install django
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Tests
        run: |
          cd Lab3
          python manage.py test
          
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ secrets.TOKEN }}
          source_ref: 'backend'
          target_branch: 'master'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
