name: Docker Image CI and tests

on:
  push:
    branches: [ "backend" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
          
      - name: merge-to-master
        run: |
          git checkout -b master
          git merge backend
